version: '3.9'
services:
  # mariadb:
  #   image: docker.io/bitnami/mariadb:10.6
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #     - MARIADB_USER=bn_myapp
  #     - MARIADB_DATABASE=bitnami_myapp

  laravel:
    image: docker.io/bitnami/laravel:9
    ports:
      - '80:8000'
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel
      - DB_DATABASE=laravel
    volumes:
      - './src:/app'
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
    volumes:
      - mysql_laravel_proyect:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

volumes:
  mysql_laravel_proyect: